### ISSUE TITLE
Can I use your plugin to read Lightroom exported keywords in Metadata for use on my Wordpress site (in image galleries). I have no programming experience but am just getting someone to redo my website starting next week, so they can do it. If so is there a particular theme or gallery she should use? Please? 

### ISSUE THREAD

**Issue by SallyHG** [smartfigures-dar/feedback_repo#10]
**What is your problem**

A clear and concise description of what the problem is. Ex. I want to do ..., but [...]

**Link to the page where you have the problem (if relevant)**

https://gin.g-node.org/larkumlab [...]

**Comment by jcolomb** [comment]
I am not sure I understand the question, but the answer is probably no, as we are not working with wordpress.

**Comment by SallyHG** [comment]
Thanks anyway ☺ 

⁣Sent from BlueMail ​
