### ISSUE TITLE
Multiple author contributions - write access for all ?! 

### ISSUE THREAD

**Issue by HannahSonntag** [smartfigures-dar/feedback_repo#7]
When a figure is set to public with multiple authors: 
would each author need to agree to putting the figure public? Would each author get write access to all aspects of the smartfigure?(Eg. Edit title/keywords the figure itsself) 

Probably not: Its similar to published papers: the ‘corresponding authors’ (=the ‘admin' or the ‘owner' of the SmartFigure) has the responsibility to gather agreements.   

This has to be very clear maybe through the pre-public checklist and the popup when people share figs with a public group.

**Comment by jcolomb** [comment]
Pre-publication workflow:
we want to  give write access to authors.
we want to have authors/contributors in the metadata.

Can we do it in one unique step ? Can we do it in one step without orcid integration.

**Comment by jcolomb** [comment]
authors: read access
corresponding authors: read and write accees,

performed in one step, adding authors that have a profile.
implememented in dev
